tile center
lovell/sharp pull request #2397
Opened 2020-10-04 12:36 UTC by beig

added center/centre image in tile

2020-10-06 18:20 UTC, lovell requested changes
Hi, thank you for this PR, I've left a couple of comments inline that should help you with those failing tests.

2020-10-06 18:20 UTC, lovell commented on lib/output.js
> +        this.options.centre = options.centre || options.center;
Please can you use `this._setBooleanOption()` to set this boolean property, preferably with a `tile` prefix for consistency, i.e. `tileCentre`. You may also want to set it to a default value of `false` when `this.options` is created in the constructor.

2020-10-06 18:20 UTC, lovell commented on src/pipeline.cc
> +    baton->centre = sharp::AttrAsBool(options, "centre");
The `if` wrapper can be removed by ensuring `this.options.tileCentre` defaults to `false` in JS land.

2020-10-07 12:35 UTC, beig commented
I hopefully correctly applied your suggestions

2020-10-07 21:49 UTC, lovell commented
Thank you for the update, it looks like there is a linting error to deal with.

2020-10-08 08:51 UTC, merged

2020-10-08 08:52 UTC, lovell commented
Brilliant, thank you very much, this will be in v0.26.2.