feat: exposing vips_gaussnoise operation
lovell/sharp pull request #2527
Opened 2021-01-12 17:13 UTC by alza54

Gaussian noise feature respecting the [proposed API](https://github.com/lovell/sharp/pull/2525#issuecomment-757448918)

2021-01-12 17:30 UTC, alza54 commented on src/common.cc
> +          image = image.bandjoin(bands).colourspace(VIPS_INTERPRETATION_sRGB).cast(VipsBandFormat::VIPS_FORMAT_UCHAR);
I supposed that converting to (s)RGB colour space even in case for only 1 channel is an expected behaviour.

2021-01-13 20:56 UTC, lovell requested changes
Fantastic, thank you very much for this. I've left a couple of questions/comments inline that will probably need addressing, then we can merge this useful feature.

2021-01-13 20:56 UTC, lovell commented on lib/input.js
> +        throw new Error('Expected valid width, height and channels to create a new input image');
Please can you add a unit test that covers this line.

2021-01-13 20:56 UTC, lovell commented on src/common.cc
> +          image = image.bandjoin(bands).colourspace(VIPS_INTERPRETATION_sRGB).cast(VipsBandFormat::VIPS_FORMAT_UCHAR);
1 and 2 channel images should probably be `VIPS_INTERPRETATION_B_W` (3 and 4 can be `VIPS_INTERPRETATION_sRGB`).

2021-01-16 14:02 UTC, lovell approved these changes
Marvellous, thank you very much.

2021-01-16 14:03 UTC, merged