Update output.js
lovell/sharp pull request #2581
Opened 2021-02-16 13:45 UTC by florian-busch

This is my first pull request (at all!). Please let me know if something needs improvement.

I added a const formatLowerCase at line 190 that saves the lowerCase version of the format parameter. 
At 192 and 194 I replaced "format" with "formatLowerCase.

2021-02-16 15:08 UTC, lovell requested changes
Hi, thank you very much for the PR.

Please can you run `npm test` locally to ensure all the linting rules and unit tests still pass. If you could also add a test to cover this new feature e.g. `.toFormat('JPEG')` that would be even better.

I've also left one comment inline that will need addressing.

2021-02-16 15:08 UTC, lovell commented on lib/output.js
> +  const formatLowerCase = format.toLowerCase()
`format` might be an object so the call to `.toLowerCase()` needs to happen on the next line, something like the following (untested):
```diff
- ... formats.get(is.object(format) && is.string(format.id) ? format.id : format);
+ ... formats.get((is.object(format) && is.string(format.id) ? format.id : format).toLowerCase());
```

2021-02-17 15:06 UTC, florian-busch commented
Updated output.js to accept upper case characters.
Created test for string and object input toFormat(). 
All tests work locally. Please let me know if other problems occur

2021-02-17 20:44 UTC, lovell approved these changes

2021-02-17 20:46 UTC, merged

2021-02-17 20:46 UTC, lovell commented
Brilliant, thank you very much.

2021-02-22 21:15 UTC, lovell commented
v0.27.2 now available, thanks for the PR.