[WIP] Add attention_x and attention_y as output to attention based crop
lovell/sharp pull request #3470
Opened 2022-11-26 14:21 UTC by ejoebstl

Hello,

This is in response to #3084 and builds upon the following [PR in libvips](https://github.com/libvips/libvips/pull/3164).

The code change exposes the coordinates of the center of attention when using attention based smart cropping.

I'd suggest to merge this PR after my changes are included in libvips.

2022-12-01 16:38 UTC, ejoebstl commented
The relevant changes will be released in version 8.14 of libvips.

2022-12-01 18:36 UTC, lovell requested changes
Hello, thanks for the PR, I've left a couple of questions/comments inline that I think will need addressing.

2022-12-01 18:36 UTC, lovell commented on src/pipeline.cc
> +        info.Set("attentionCenterX", static_cast<int32_t>(baton->attentionCenterX));
Please can these be named `attentionX` and `attentionY` to match libvips.

2022-12-01 18:36 UTC, lovell commented on src/pipeline.cc
> +            baton->attentionCenterX = static_cast<int>(attention_x * jpegShrinkOnLoad);
I think there's also `scale` (for WebP and SVG input) to consider here. Perhaps add a test for this also?

2023-01-13 08:50 UTC, ejoebstl commented
@lovell - Thank you, feedback adressed.

The newest libvips release also includes the attentionX and attentionY fields. 

Is there an approximate timeline for the next release?

2023-01-13 14:52 UTC, lovell commented
Thanks for the updates, please can you rebase against the `flow` branch (I've changed the target branch of this PR to match) as that has the latest libvips with support for this feature.

2023-01-13 17:17 UTC, ejoebstl commented
Done 🙌

2023-01-15 20:43 UTC, lovell commented
Thanks for the updates, LGTM. The Windows failures are due to what appears to be a possible bug in that latest `node-addon-api`, which I've pinned to the last-known good release via commit https://github.com/lovell/sharp/commit/a9bd0e79f8dbf034f1a839bbf231aebdb5393414

2023-01-15 20:43 UTC, lovell approved these changes

2023-01-16 09:20 UTC, merged

2023-01-16 09:30 UTC, lovell commented
Danke schön Emanuel!