Update install.md
lovell/sharp pull request #3568
Opened 2023-02-23 12:02 UTC by cychub

2023-02-23 15:47 UTC, lovell requested changes

2023-02-23 15:47 UTC, lovell commented on docs/install.md
> +`/path/v1.2.3/sharp-v1.2.3-napi-v5-platform-arch.tar.gz`.
The local prebuilds feature of prebuild-install doesn't add the version-as-a-path-component, so please can you remove the change on this line.

https://github.com/prebuild/prebuild-install#local-prebuilds

2023-02-23 15:47 UTC, lovell commented on docs/install.md
> +`https://hostname/path/v1.2.3/sharp-v1.2.3-napi-v5-platform-arch.tar.gz`.
Good spot, thank you.

2023-02-27 08:32 UTC, cychub commented on docs/install.md
> +`https://hostname/path/v1.2.3/sharp-v1.2.3-napi-v5-platform-arch.tar.gz`.
updated

2023-02-28 18:12 UTC, lovell commented on docs/install.md
> +`/path/v1.2.3/sharp-v1.2.3-napi-v5-platform-arch.tar.gz`.
Thanks for the update, it looks like this line change is still present so marking as unresolved.

2023-03-12 12:58 UTC, merged

2023-03-12 12:58 UTC, lovell commented
Thank you very much!